language: python

install:
  - pip install -r requirements.txt --prefer-binary
  - pip install .
  - pip install sphinx m2r sphinx_rtd_theme

script: 
  - pytest
  - cd docs
  - make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TOKEN  # shared with travis-ci.org dashboard
  keep-history: true
  target_branch: master
  on:
    branch: master
  local_dir: docs/_build/html/
